"""Unified path helper for the CRISPI data tree.

Single source of truth for where the platform reads and writes data. Implements
a centralized layout in `core.paths`. Consumers must NOT hardcode path
strings — they import the constants below.

Layout:

    <DATA_ROOT>/
    ├── config/        operator-supplied + persistent (calibration.npy, rois.npz, mask_map.csv)
    ├── assets/        generated by calibration pipeline (homography, sl_patterns, diagnostic)
    │   ├── homography/
    │   ├── sl_patterns/
    │   └── diagnostic/
    ├── runs/<TS>/     per-experiment science outputs (result.npz, ground_truth.npz, experiment_meta.json)
    ├── recordings/<TS>/  per-experiment heavy data (recording.tiff, sl_captures/)
    └── cache/         transient compute (LUTs, debug frames; safe to delete anytime)

Resolution:

    DATA_ROOT = $STIM_DATA_ROOT or./data (relative to CWD if env var unset)

Why an env var instead of CLI flag: every consumer that needs paths reads
from here, not from argparse. Operators override globally via the env var
(e.g., `export STIM_DATA_ROOT=/mnt/datadrive`), tests inject a temp dir
via `monkeypatch.setenv`.

The migration from the legacy layout (Assets/Generated/, root mask_map.csv,
data/experiments/) is happening **per module during audit**, not as one
atomic commit. Until each module migrates, its own hardcoded path strings
remain in place. 
"""

from __future__ import annotations

import os
from datetime import datetime
from pathlib import Path
from typing import Final


_ENV_VAR: Final[str] = "STIM_DATA_ROOT"
_DEFAULT: Final[str] = "data"


def _resolve_root() -> Path:
    """Read DATA_ROOT lazily — env var captured at call time."""
    return Path(os.environ.get(_ENV_VAR, _DEFAULT))


def data_root() -> Path:
    """Return the data tree root.

    Read on every call (not cached) so tests can override via
    monkeypatch.setenv without restarting the process.
    """
    return _resolve_root()


def config_dir() -> Path:
    return data_root() / "config"


def assets_dir() -> Path:
    return data_root() / "assets"


def homography_dir() -> Path:
    return assets_dir() / "homography"


def sl_patterns_dir() -> Path:
    return assets_dir() / "sl_patterns"


def diagnostic_dir() -> Path:
    return assets_dir() / "diagnostic"


def runs_dir() -> Path:
    return data_root() / "runs"


def recordings_dir() -> Path:
    return data_root() / "recordings"


def cache_dir() -> Path:
    return data_root() / "cache"


def run_dir(timestamp: str | None = None, *, create: bool = True) -> Path:
    """Return (and optionally create) data/runs/<TS>/.

    Default timestamp format: YYYYMMDD_HHMMSS. Consumers pass an explicit
    timestamp when they need to write multiple files into the same run dir
    across function boundaries; otherwise default to "now".
    """
    if timestamp is None:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    p = runs_dir() / timestamp
    if create:
        p.mkdir(parents=True, exist_ok=True)
    return p


def recording_dir(timestamp: str | None = None, *, create: bool = True) -> Path:
    """Return (and optionally create) data/recordings/<TS>/."""
    if timestamp is None:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    p = recordings_dir() / timestamp
    if create:
        p.mkdir(parents=True, exist_ok=True)
    return p


def ensure_layout() -> None:
    """Idempotently create the top-level directories.

    Called once at process startup by modules that need the layout to
    exist before writing. config/ and assets/ subdirs get created on
    first use (homography_dir(), etc.); ensure_layout() guarantees the
    parents.
    """
    for d in (config_dir(), assets_dir(), runs_dir(), recordings_dir(),
              cache_dir(), homography_dir(), sl_patterns_dir(),
              diagnostic_dir()):
        d.mkdir(parents=True, exist_ok=True)


# Convenience re-exports for the common case (read-only constants — these
# evaluate ONCE at import time using whatever env var was set at the time
# the importing module loaded. Tests that need to override at runtime
# should call the functions above, not the constants).
DATA_ROOT: Path = _resolve_root()
CONFIG_DIR: Path = DATA_ROOT / "config"
ASSETS_DIR: Path = DATA_ROOT / "assets"
HOMOGRAPHY_DIR: Path = ASSETS_DIR / "homography"
SL_PATTERNS_DIR: Path = ASSETS_DIR / "sl_patterns"
DIAGNOSTIC_DIR: Path = ASSETS_DIR / "diagnostic"
RUNS_DIR: Path = DATA_ROOT / "runs"
RECORDINGS_DIR: Path = DATA_ROOT / "recordings"
CACHE_DIR: Path = DATA_ROOT / "cache"
